spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: "ansalsdn15"

  datasource:
    url: jdbc:mysql://localhost:3306/redis?serverTimezone=Asia/Seoul
    username: root
    password: "ansalsdn15"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    redis.spring.redis: DEBUG #로깅 레벨 설정